# https://stackoverflow.com/questions/62403030/terraform-wait-till-the-instance-is-reachable
# https://www.reddit.com/r/ansible/comments/b6jbo6/alternative_to_host_key_checking_false_for_first/
# https://stackoverflow.com/questions/32297456/how-to-ignore-ansible-ssh-authenticity-checking

---
- name: Get new keys
  hosts: all
  gather_facts: no
  tasks:
    - name: Sleep for 60 seconds, then begin
      delegate_to: localhost
      wait_for:
        timeout: 60

    - name: Scan for new keys
      delegate_to: localhost
      register: host_keys
      changed_when: false
      shell: |
        ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
