---
- name: Disable Cloud-Init
  hosts: all
  become: yes
  remote_user: user1
  vars:
    ansible_ssh_private_key_file: "/build-lab/prox/.ssh/prox"
  tasks:
    - name: create /etc/cloud/cloud-init.disabled
      file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
