# I didn't realize that Azure Vault is only available to subscribers
# of Azure online.  While we could use Hashicorp Vault, this is the portion
# of the project I'm trying to use a few external tools as possible.

trigger: none # not "don't trigger", just "don't trigger by pushing code, only by script (manually)

parameters:
- name: KERNEL_VERSION
  type: string

variables:
- group: ModuleSigningSecrets

jobs:
- job: CompileAndSignKernelModule
  pool:
    name: 'Linux-agent-pool'

  # I misunderstood this part, but this is actually only available in Azure on the web, not on-prem.
  steps:
  - task: AzureKeyVault@2 # the @2 is mandatory!
    inputs:
      azureSubscription: 'service-connection-for-vault' # This one is mandatory too.  In our case, it specifically means the connection to the server.
      KeyVaultName: 'vault-name'
      SecretsFilter: 'ModuleSigningKey'
    displayName: 'Get Private Key from Vault'

  - script: |
      echo "Setting up environment for kernel version $(KERNEL_VERSION)"
      export KERNEL_HEADERS="/path/to/shared/headers/$(KERNEL_VERSION)"
    displayName: 'Setup Environment'

  - script: |
      make KERNEL_HEADERS=$KERNEL_HEADERS -f $(Build.SourcesDirectory)/Makefile
    displayName: 'Compile Kernel Module'

  - script: |
      # Save the private key to a file
      echo "$(ModuleSigningKey)" > private_key.priv
      
      # Sign the module
      /usr/src/linux-headers-$(KERNEL_VERSION)/scripts/sign-file sha256 ./private_key.priv ./private_key.der $(Build.SourcesDirectory)/*.ko
      
      # Clean up
      shred -u private_key.priv
    displayName: 'Sign Kernel Module'

  - publish: $(Build.SourcesDirectory)/*.ko
    artifact: signed_kernel_module_$(KERNEL_VERSION)

